### PR TITLE
Official OMB Number added to front page

### PR DESCRIPTION
**Pull request by mhines-usgs**
/play vuvuzela

### CODE REVIEW

**Comment by lawinslow** [comment]
9 months in the making...

**Comment by mhines-usgs** [comment]
July 22, 2014 - 1st meeting to discuss with USGS PRA Info Collections Clearance Officer
Sep 12, 2014 - 60 day notice posted (Submitted 9/5/2014)
Nov 12, 2014 - 60 day notice closed (no comments)
Jan 21, 2015 - 30 day notice posted (submitted 1/14/2015)
Feb 20, 2015 - 30 day notice closed (no comments)
Mar 25, 2015 - OMB Notice of Action given by OMB, 1028-0113

**Comment by mhines-usgs** [comment]
From and including: Friday, September 12, 2014
To, but not including Wednesday, March 25, 2015

Result: 194 days

It is 194 days from the start date to the end date, but not including the end date

Or 6 months, 13 days excluding the end date

Alternative time units
194 days can be converted to one of these units:
16,761,600 seconds
279,360 minutes
4656 hours
194 days
27 weeks and 5 days

**Comment by jiwalker-usgs** [comment]
or you can look at it as 0.00531154 centuries

**Comment by mhines-usgs** [comment]
We also really should account for the 

Excluded 28 Saturdays
Excluded 28 Sundays
Excluded 7 holidays:
- Columbus Day (Monday, October 13, 2014)
- Veterans Day (Tuesday, November 11, 2014)
- Thanksgiving Day (Thursday, November 27, 2014)
- Christmas Day (Thursday, December 25, 2014)
- New Year's Day (Thursday, January 1, 2015)
- Martin Luther King Day (Monday, January 19, 2015)
- Presidents' Day (Washington's Birthday) (Monday, February 16, 2015)

**Comment by mhines-usgs** [comment]
So really, we're talking 131 days. That's not terrible...

**Comment by lawinslow** [comment]
This pull request has gone weird places.

**Pull request merged**
