### PR TITLE
Don't style numbers like phone numbers in iPlover

### PR DESCRIPTION
**Pull request by mhines-usgs**
:iphone:

@lawinslow can you confirm this will make a difference?

### CODE REVIEW

**Comment by lawinslow** [comment]
Is this for text entered into fields?

**Comment by mhines-usgs** [comment]
@lawinslow no, it's for the blue omb number displayed on the home/login screen

**Comment by mhines-usgs** [comment]
Some other comments here: https://trello.com/c/ff6Qimas

**Comment by lawinslow** [comment]
image

**Pull request merged**
